name: Check

permissions:
    checks: write

on:
    pull_request:
        paths-ignore:
            - 'documentation/**'
            - '*.md'
    push:
        branches:
            - master
        paths-ignore:
            - 'documentation/**'
            - '*.md'

jobs:
    test:
        name: Run tests

        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      task: jvmTest
                    - os: ubuntu-latest
                      task: jsTest
                    - os: macos-latest
                      task: iosSimulatorArm64Test

        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup JDK 17
              uses: actions/setup-java@v4
              with:
                  distribution: 'adopt'
                  java-version: '17'

            - name: Setup Firefox browser
              if: matrix.task == 'jsTest'
              uses: browser-actions/setup-firefox@v1
            - run: firefox --version
              if: matrix.task == 'jsTest'

            - name: Run ${{ matrix.task }}
              run: ./gradlew ${{ matrix.task }} --stacktrace

            - name: Publish JVM report
              uses: mikepenz/action-junit-report@v4
              if: matrix.task == 'jvmTest' && (success() || failure())
              with:
                  check_name: JVM
                  report_paths: 'logger/build/test-results/jvmTest/TEST-*.xml'

            - name: Publish NodeJS report
              uses: mikepenz/action-junit-report@v4
              if: matrix.task == 'jsTest' && (success() || failure())
              with:
                  check_name: NodeJS
                  report_paths: 'logger/build/test-results/jsNodeTest/TEST-*.xml'

            - name: Publish Browser report
              uses: mikepenz/action-junit-report@v4
              if: matrix.task == 'jsTest' && (success() || failure())
              with:
                  check_name: Browser
                  report_paths: 'logger/build/test-results/jsBrowserTest/TEST-*.xml'

            - name: Publish iOS report
              uses: mikepenz/action-junit-report@v4
              if: matrix.task == 'iosSimulatorArm64Test' && (success() || failure())
              with:
                  check_name: iOS
                  report_paths: 'logger/build/test-results/iosSimulatorArm64Test/TEST-*.xml'